### ISSUE TITLE
Add support for bulk APIs

### ISSUE THREAD

**Issue by jporter-dev** [chrislee35/passivetotal#1]
Is there currently any support for the bulk APIs, or any interest in supporting them? I am trying to use them for queries and would prefer to do a single bulk API request versus multiple single requests. If this is currently unsupported, I am willing to do the legwork to add this feature.

**Comment by chrislee35** [comment]
I'm not sure if I missed it or if this was added to the API later.  It is now supported in Gem version 1.0.3.  Please test and approve me to close this issue.

**Comment by jporter-dev** [comment]
I'm not entirely sure when the bulk stuff was added, but I noticed you only added the bulk classification endpoint, when there are a few [others](https://api.passivetotal.org/api/docs/#api-Enrichment). I assume it should be fairly simple to add this, since the only difference between the regular and bulk APIs are the /bulk/ in the URL, and the query including an array rather than a single value.

**Comment by chrislee35** [comment]
I added the remaining 3: added bulk query for enrichment, malware, and osint
You should find it in version 1.0.4.  thanks for catching that.  I don't know how I missed it.
Please test and approve.

**Comment by jporter-dev** [comment]
The updates look great, thank you for pushing that out so quickly.

**Comment by chrislee35** [comment]
My pleasure.  I hope this serves you well.
